### ISSUE TITLE
Uploading to incorrect endpoint

### ISSUE THREAD

**Issue by asad-c** [aadje/VSTS-Extensions#3]
Output from log:

Uploading to https://mysubdomain-dev.scm.azurewebsites.net/api/zipdeploy

I don't know where the azurewebsites.net is coming from, it should be uploading to:

https://mysubdomain-dev.scm.mydomain.com/api/zipdeploy

**Comment by aadje** [comment]
your-appservice-name.azurewebsites.net is the default domain which is automatically created by Azure.
your-appservice-name.scm.azurewebsites.net is the default domain for the Kudu scm management site which is also automatically created by Azure.

When configuring a custom domain for an app service it's only bound to the main site.
I don't know if it's possible (and if there is a good reason) to bind a custom domain to the Kudu scm site.

**Comment by asad-c** [comment]
I managed to find a another method for ZipDeploy; I changed the build agent to Ubuntu and the Azure App Service Deploy task uses ZipDeploy instead of MSDeploy. MSDeploy doesn't work for me because of proxy issues. This may help someone else.
